In [2]:
import os, sys
import dotenv

dotenv.load_dotenv('../.env')    
PATH_DATA = os.environ.get('PATH_OPENSKY') + os.environ.get('PATH_REL_DATA')

PATH_DATA

'/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/'

In [3]:
import pandas as pd

df = pd.read_csv(PATH_DATA + '/feed_bookmarks.csv')
df

           Science   408833  202309192111
0          Science   204992  202307290107
1          Science  1798953  202309232103
2          Science  1428436  202311051321
3          Science   976464  202309131041
4          Science   325292  202310130606
...            ...      ...           ...
18318  AcademicSky   214659  202308211804
18319  AcademicSky   265142  202308221136
18320  AcademicSky   220804  202308270639
18321  AcademicSky    31857  202308012140
18322  AcademicSky  1171946  202310211249

[18323 rows x 3 columns]

In [6]:
df3 = pd.read_csv(PATH_DATA + '/graphs/quotes.csv')

df3

          836672  559307  20230826
0          45957   45957  20231222
1          45957   45957  20231222
2          45957   86070  20231108
3          45957  703707  20231023
4         207389  207387  20231017
...          ...     ...       ...
12085577  148616  546912  20231024
12085578  148616   41511  20231021
12085579  770644   12285  20231229
12085580   67275  558853  20231010
12085581   67275    6738  20230901

[12085582 rows x 3 columns]

In [7]:
user_posts_files = os.listdir(PATH_DATA + '/user_posts')
user_posts_files[0]

'288811.jsonl'

In [8]:
df = pd.read_json(PATH_DATA + '/user_posts/' + user_posts_files[0], lines=True)
df

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
0,3638735,288811,bsky.social,1976-05-31 15:06:01.140,聞き上手。\nA good listener.\n\n#虎#鬼,[jpn],0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3638736,288811,bsky.social,1976-05-31 15:05:50.256,仲良し。\nBest buddies.\n \n#虎#鬼,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3638737,288811,bsky.social,1976-05-31 15:05:40.458,ハートをプレゼント。\nheart's present\n\n#ホワイトデー#ハート,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3638738,288811,bsky.social,1976-05-31 15:05:30.558,ドット絵ジョルノ9分割。\njojo fan art.,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3638739,288811,bsky.social,1976-05-31 15:05:30.302,朝日を浴びる。\nMorning sun.,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3638740,288811,bsky.social,1976-05-31 15:05:00.329,力士。\nsumo wrestler.\n\n#相撲#sumo#大阪場所#三月場所#らくがき...,[jpn],3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3638741,288811,bsky.social,1976-05-31 15:04:42.314,おはようございます🐶😃❤️\n良い週末をお過ごしください✨✨✨✨🍀❣️\n\n２枚目、昨日公...,[jpn],7,0,1,NaN,NaN,NaN,NaN,3638742.0,2042093.0,NaN,NaN,NaN,NaN,NaN
7,3638743,288811,bsky.social,1976-05-31 15:04:40.943,えええええええええ………\n\nいっぱいの楽しいを、ありがとうございました…ｯ!!!,[jpn],4,0,1,NaN,NaN,NaN,NaN,3638744.0,602538.0,511107.0,23351.0,NaN,NaN,NaN
8,3638745,288811,bsky.social,1976-05-31 15:04:40.945,敬意と感謝を込めて🥲\n\n#ドラゴンボール#鳥山明#孫悟空#doragonball,[jpn],8,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3638746,288811,bsky.social,1976-05-31 15:04:40.337,春を想う。\nThink of spring.\n\n#猫#ねこ#春#花#らくがき#イラスト,[jpn],5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3638747,288811,bsky.social,1976-05-31 15:04:31.345,スティッキーフィンガーズとゴールドエクスペリエンス。\njojo fan art.\n\n#...,[jpn],7,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3638748,288811,bsky.social,1976-05-31 15:04:31.343,ジョルノとブチャラティ\njojo fan art.\n\n#ジョジョ５部#ジョルノ・ジョバ...,[jpn],4,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3638749,288811,bsky.social,1976-05-31 15:04:20.314,ブチャラティとピザ🍕\njojo.\nfan art.\n\n#ジョジョ#ジョジョ５部#ブチ...,[jpn],7,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3638750,288811,bsky.social,1976-05-31 15:04:10.316,ねことバナナ🍌\nCat and banana.\n\n#猫#ネコ#バナナ#らくがき,[jpn],5,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3638751,288811,bsky.social,1976-05-31 15:04:00.346,男の子とねこ。\nA boy and a cat.\n\n#らくがき#ねこ#猫#男の子#イラスト,[jpn],5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,3638752,288811,bsky.social,1976-05-31 15:03:50.338,ひな祭り🎎\nHinamaturi.\n\n#ひな祭り#雛祭り#お雛様#桃の節句,[jpn],5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3638753,288811,bsky.social,1976-05-31 15:03:40.228,さ、寒い‼︎\nVery cold‼︎\n\n#冬#防寒#女の子#イラスト#らくがき,[jpn],9,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3638754,288811,bsky.social,1976-05-31 15:03:30.647,青い首巻き。\nBlue scarf.\n\n#猫#ねこ#猫イラスト#らくがき#スカーフ,[jpn],7,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3638755,288811,bsky.social,1976-05-31 14:51:30.542,洗顔✨\n\nwash my face.\n\n#女の子イラスト#落書き#らくがき,[jpn],5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3638756,288811,bsky.social,1976-05-31 14:51:20.411,ねこの使者。\nthe messenger of the cat.\n\n#猫#ねこ#ネコ#...,[jpn],9,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,3638757,288811,bsky.social,1976-05-31 14:51:10.800,飛行機雲。\ncontrail.\n\n#飛行機雲#雲#空#落書き,[jpn],3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,3638758,288811,bsky.social,1976-05-31 14:51:00.312,タンクトップねこ。\nA cat in a tank top.\n\n#猫#ねこ#タンクトッ...,[jpn],6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3638759,288811,bsky.social,1976-05-31 14:50:50.434,らくがき②\n\n火の粉ねこ\nSpark cat.\n\n#猫#ねこ#落書き#イラスト,[jpn],6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3638760,288811,bsky.social,1976-05-31 14:50:50.039,黄色いさかな\nYellow fish.\n\n#魚#さかな#黄色#落書き,[jpn],3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,3638761,288811,bsky.social,1976-05-31 14:50:41.159,空とねこ。\nThe sky and the cat.\n\n#猫#空#らくがき,[jpn],6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3638762,288811,bsky.social,1976-05-31 14:50:30.458,風に吹かれるうさぎ。\nWind and rabbit.\n\n#うさぎ#rabbit#らくがき,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,3638763,288811,bsky.social,1976-05-31 14:50:20.532,猫の日②\n\n壁の向こうから猫。\na cat beyond the wall.\n\n#...,[jpn],5,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,3638764,288811,bsky.social,1976-05-31 14:50:20.301,猫の日\n\nCat Day.\nNatinal Cat Day.\n\n#猫の日#ねこ#ネコ,[jpn],4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,3638765,288811,bsky.social,1976-05-31 14:50:10.524,見てるねこ②\n引きの図\n\nThe cat is watching.\n\n#猫の日前日...,[jpn],9,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,3638766,288811,bsky.social,1976-05-31 14:50:10.001,見てるねこ\nThe cat is watching.\n\n#猫の日#猫#ねこ,[jpn],5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,3638767,288811,bsky.social,1976-05-31 14:50:00.409,ゴールデンカムイ、鯉登音之進。\n\n映画実写化では誰がするのかな\n\nGolden Ka...,[jpn],4,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,3638768,288811,bsky.social,1976-05-31 14:49:51.519,原っぱねこ。\nA cat in the field.,[jpn],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,3638769,288811,bsky.social,1976-05-31 14:49:40.250,もうすぐ猫の日イラスト。\n\nにゃん仏、迷えるにゃんこを導くの図。,[jpn],6,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
len(user_posts_files)

705683

In [10]:
df.iloc[0]

post_id                                       3638735
user_id                                        288811
instance                                  bsky.social
date                       1976-05-31 15:06:01.140000
text                  聞き上手。\nA good listener.\n\n#虎#鬼
langs                                           [jpn]
like_count                                          0
reply_count                                         0
repost_count                                        0
reply_to                                          NaN
replied_author                                    NaN
thread_root                                       NaN
thread_root_author                                NaN
repost_from                                       NaN
reposted_author                                   NaN
quotes                                            NaN
quoted_author                                     NaN
labels                                            NaN
sent_label                                        NaN
sent_score                                        NaN
Name: 0, dtype: object