In [2]:
import os, sys
import dotenv

import pandas as pd
import numpy as np

dotenv.load_dotenv('../.env')    
PATH_DATA = os.environ.get('PATH_OPENSKY') + os.environ.get('PATH_REL_DATA')
PATH_DATA

'/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/'

In [9]:
feed_files = os.listdir(PATH_DATA + 'feed_posts')
feed_file = feed_files[0]
path_feed_file = PATH_DATA + 'feed_posts/' + feed_file  
feed_files, path_feed_file

(['Science.jsonl.gz',
  'Political Science.jsonl.gz',
  'BookSky.jsonl.gz',
  'Blacksky.jsonl.gz',
  'Game Dev.jsonl.gz',
  'AcademicSky.jsonl.gz',
  '#Disability.jsonl.gz',
  'News.jsonl.gz',
  "What's History.jsonl.gz",
  'GreenSky.jsonl.gz',
  '#UkrainianView.jsonl.gz'],
 '/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/feed_posts/Science.jsonl.gz')

In [65]:
import gzip
import json

def load_jsonl(input_path) -> list:
    """
    Read list of objects from a JSON lines file.
    """
    count = 0
    data = []
    with gzip.open(input_path, 'r') as f:
        for line in f:
            line = f.readline().decode('utf-8').rstrip()
            data.append(json.loads(line))
            count += 1

    print(f'Loaded {count} lines from {input_path}') 
    return data 

    #cols = ['post_id', 'user_id', 'instance', 'date', 'text', 'langs', 'repost_count', 'reply_to', 'replied_author', 'thread_root', 'thread_root_author', 'quotes', 'quoted_author', 'labels']
    #return pd.DataFrame(lines, columns=cols)

load_jsonl(path_feed_file)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [64]:
data = []
with gzip.open(path_feed_file, 'r') as f:
    for line in range(10000):
        line = f.readline().decode('utf-8').rstrip()
        data.append(json.loads(line))
pd.DataFrame(data)

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,quotes,quoted_author,labels
0,134430,10507,bsky.social,202402101508,Welcome to the Science feed!\n\nPlease read ou...,[eng],497,29,62,NaN,NaN,NaN,NaN,NaN,NaN,None
1,134430,10507,bsky.social,202402101508,Welcome to the Science feed!\n\nPlease read ou...,[eng],497,29,62,NaN,NaN,NaN,NaN,NaN,NaN,None
2,68828985,83711,bsky.social,202403182331,VERY proud of my Esri colleague Kevin Butler f...,[eng],14,0,5,NaN,NaN,NaN,NaN,NaN,NaN,None
3,182457117,1152097,bsky.social,202403182314,AI was revolutionized by an old idea (neural n...,[eng],5,2,0,NaN,NaN,NaN,NaN,NaN,NaN,None
4,12805677,165925,bsky.social,202403182314,🦈 🦑 🧪 \n\nOne of the earlier pubs (1956) about...,[eng],5,2,2,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,3465670,35868,bsky.social,202312251623,#Crustmas ends the way so many things do...wit...,[eng],58,2,17,NaN,NaN,NaN,NaN,NaN,NaN,None
9996,204913169,65551,bsky.social,202312251622,"Sun December 24, 2023: 🇦🇶 Antarctica Today\nSu...",[eng],0,1,0,204913170.0,65551.0,15964392.0,65551.0,NaN,NaN,None
9997,107174148,331091,bsky.social,202312251613,#MarineLife 🦑 #science 🧪,[eng],1,0,0,72066952.0,168995.0,72066952.0,168995.0,NaN,NaN,None
9998,6190385,134,bsky.social,202312251529,Gonna talk climate with contrary family member...,[eng],44,1,7,NaN,NaN,NaN,NaN,NaN,NaN,None
9999,83876298,103530,bsky.social,202312251400,🪶🌎🧪,None,25,0,3,NaN,NaN,NaN,NaN,NaN,NaN,None

In [4]:
with 
df = pd.read_json(PATH_DATA + '/feeds_posts/Blacksky.jsonl.gz', lines=True, compression='gzip')
df

/tmp/ipykernel_216535/2186299374.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(PATH_DATA + '/feeds_posts/Blacksky.jsonl.gz', lines=True, compression='gzip')

ValueError: Expected object or value

In [9]:
df.isna().sum()

instance               2426
langs                 12909
min_date               2426
max_date               2426
mean_sent_score      338029
mean_like_count        2426
mean_reply_count       2426
mean_repost_count      2426
n_posts                2426
caught_exception          0
dtype: int64

In [11]:
df.langs = df.langs.str.split(',')
df

,instance,langs,min_date,max_date,mean_sent_score,mean_like_count,mean_reply_count,mean_repost_count,n_posts,caught_exception
288811,bsky.social,[jpn],1976-05-31 14:49:40.250,1976-05-31 15:06:01.140,NaN,4.636364,0.000000,0.242424,33.0,False
527934,bsky.social,"[eng, heb, jpn, fra]",1976-05-30 12:23:51.918,1976-05-31 15:06:22.021,0.824409,18.211009,0.616972,7.187691,2616.0,False
1632691,bsky.social,[spa],1976-05-30 13:16:31.226,1976-05-30 13:16:31.226,NaN,2.000000,1.000000,0.000000,1.0,False
1909409,bsky.social,[jpn],1976-05-31 14:48:11.431,1976-05-31 14:48:11.431,NaN,1.000000,0.000000,0.000000,1.0,False
2902501,bsky.social,[kor],1976-05-30 12:59:01.311,1976-05-31 14:51:00.209,NaN,0.500000,0.100000,0.000000,10.0,False
...,...,...,...,...,...,...,...,...,...,...
495380,bsky.social,[eng],1976-05-30 12:40:30.146,1976-05-31 14:48:01.457,0.790667,0.800000,0.173333,0.026667,75.0,False
502241,bsky.social,[eng],1976-05-31 14:47:42.021,1976-05-31 14:47:42.304,0.800889,3.777778,1.444444,1.222222,9.0,False
1652601,bsky.social,"[spa, eng, cat, jpn]",1976-05-30 12:09:11.814,1976-05-31 15:03:31.700,0.770500,87.579186,3.936652,33.321267,221.0,False
1838341,bsky.social,[por],1976-05-30 12:23:50.927,1976-05-30 12:24:10.012,NaN,13.600000,1.400000,3.400000,5.0,False
3401925,esq,[eng],1976-05-30 13:47:41.035,1976-05-31 15:05:40.127,0.727286,0.411765,0.215686,0.098039,51.0,False

In [15]:
df.langs.explode().value_counts().head(20)

langs
eng    390937
jpn    277884
deu     68447
spa     55683
fra     51556
por     34400
kor     28512
zho     25951
rus     22243
nld     17063
ita     14246
swe     10952
fin     10153
ukr     10057
ell      8265
tha      7986
pol      7265
tur      7265
ara      5939
vie      5913
Name: count, dtype: int64