In [1]:
import os, sys
import dotenv

import pandas as pd
import numpy as np

dotenv.load_dotenv('../.env')    
PATH_DATA = os.environ.get('PATH_OPENSKY') + os.environ.get('PATH_REL_DATA')
PATH_DATA

'/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/'

In [2]:
feed_files = os.listdir(PATH_DATA + 'feed_posts')
feed_file = feed_files[0]
path_feed_file = PATH_DATA + 'feed_posts/' + feed_file  
feed_files, path_feed_file

(['Science.jsonl.gz',
  'Political Science.jsonl.gz',
  'BookSky.jsonl.gz',
  'Blacksky.jsonl.gz',
  'Game Dev.jsonl.gz',
  'AcademicSky.jsonl.gz',
  '#Disability.jsonl.gz',
  'News.jsonl.gz',
  "What's History.jsonl.gz",
  'GreenSky.jsonl.gz',
  '#UkrainianView.jsonl.gz'],
 '/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/feed_posts/Science.jsonl.gz')

In [3]:
import gzip
import json

def load_jsonl(input_path) -> list:
    """
    Read list of objects from a JSON lines file.
    """
    data = []
    with gzip.open(input_path, 'r') as f:
        for line in f:
            try:
                line = f.readline()
                line = line.decode('utf-8')
                line = line.rstrip()
                data.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f'Error in line: {line}')
                print(e)

    print(f'Loaded {len(data)} lines from {input_path}') 

    cols = ['post_id', 'user_id', 'instance', 'date', 'text', 'langs', 'repost_count', 'reply_to', 'replied_author', 'thread_root', 'thread_root_author', 'quotes', 'quoted_author', 'labels']
    return pd.DataFrame(data)

df = load_jsonl(path_feed_file)
df

Error in line:
Expecting value: line 1 column 1 (char 0)
Loaded 16915 lines from /home/ties/Documents/00_Uni/24W/Foundations/opensky/data/feed_posts/Science.jsonl.gz

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,quotes,quoted_author,labels
0,134430,10507,bsky.social,202402101508,Welcome to the Science feed!\n\nPlease read ou...,[eng],497,29,62,NaN,NaN,NaN,NaN,NaN,NaN,None
1,182457117,1152097,bsky.social,202403182314,AI was revolutionized by an old idea (neural n...,[eng],5,2,0,NaN,NaN,NaN,NaN,NaN,NaN,None
2,17759651,558,bsky.social,202403182310,ü¶ëüß™üåé,[eng],25,0,10,NaN,NaN,NaN,NaN,17759652.0,172930.0,None
3,77009156,35868,bsky.social,202403182240,üß™,[eng],2,0,1,NaN,NaN,NaN,NaN,1431706.0,385833.0,None
4,27536774,286675,bsky.social,202403182205,Forgot üß™ ... oh well!,[eng],4,0,0,NaN,NaN,NaN,NaN,27536775.0,286675.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16910,61538753,27153,social,202306040311,Done done done\n\nFor those tagged in - if you...,None,19,2,10,14060175.0,448984.0,165392.0,27153.0,NaN,NaN,None
16911,165392,27153,social,202306022238,I have built a custom feed at https://bsky.app...,None,65,22,20,NaN,NaN,NaN,NaN,NaN,NaN,None
16912,71957455,814481,bsky.social,202306020625,This reduction in biological maintenance is ev...,None,0,1,0,71957456.0,814481.0,71957428.0,814481.0,NaN,NaN,None
16913,71957467,814481,bsky.social,202306020604,One of the striking aspects of isomyosmine is ...,None,0,1,0,71957468.0,814481.0,71957428.0,814481.0,NaN,NaN,None
16914,26319660,6547,bsky.social,202306010643,üß¨üî¨‚öóÔ∏èüî≠ü•ºüß™üë©üèª‚Äçüî¨ SCIENCE,None,1,0,0,26082396.0,10507.0,26082396.0,10507.0,NaN,NaN,None

In [80]:
df.isna().sum()

post_id                   0
user_id                   0
instance                  0
date                      0
text                      0
langs                  1042
like_count                0
reply_count               0
repost_count              0
reply_to              14711
replied_author        14711
thread_root           14711
thread_root_author    14711
quotes                14378
quoted_author         14378
labels                16914
dtype: int64

In [83]:
feed_files = os.listdir(PATH_DATA + 'feed_posts_likes')
feed_files

['AcademicSky.csv.gz',
 'GreenSky.csv.gz',
 'Science.csv.gz',
 '#Disability.csv.gz',
 'BookSky.csv.gz',
 'Game Dev.csv.gz',
 'Blacksky.csv.gz',
 'Political Science.csv.gz',
 '#UkrainianView.csv.gz',
 'News.csv.gz',
 "What's History.csv.gz"]

In [86]:
path_feed_likes_file = PATH_DATA + 'feed_posts_likes/News.csv.gz'
path_feed_likes_file

'/home/ties/Documents/00_Uni/24W/Foundations/opensky/data/feed_posts_likes/News.csv.gz'

In [87]:
pd.read_csv(path_feed_likes_file, compression="gzip")

         1499007  27155  3517724  202312212134
0        2158956  27155  3517724  202402091909
1        1248108  27155  3517724  202310271446
2         804480  27155  3517724  202402062331
3         283396  27155  3517724  202401011833
4        1920942  27155  3517724  202402072144
...          ...    ...      ...           ...
2115316  4411856  27155  3517724  202404011545
2115317  3995176  27155  3517724  202312312345
2115318  4413278  27155  3517724  202404030257
2115319   359487  27155  3517724  202402071257
2115320   905347  27155  3517724  202311170231

[2115321 rows x 4 columns]