In [1]:
import os, sys
import dotenv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dotenv.load_dotenv('../.env')    
PATH_DATA = os.environ.get('PATH_OPENSKY') + os.environ.get('PATH_REL_DATA')
PATH_USER_POSTS = PATH_DATA + 'user_posts/'
PATH_FEED_POSTS = PATH_DATA + 'feed_posts/'

In [2]:
df_news_feed = pd.read_json(PATH_FEED_POSTS + 'News.jsonl.gz', lines=True)
nos = set(df_news_feed.user_id.unique())
nos

{np.int64(9),
 np.int64(114),
 np.int64(319),
 np.int64(379),
 np.int64(625),
 np.int64(626),
 np.int64(1168),
 np.int64(1537),
 np.int64(1639),
 np.int64(2478),
 np.int64(2486),
 np.int64(3011),
 np.int64(3418),
 np.int64(4887),
 np.int64(4890),
 np.int64(5087),
 np.int64(5221),
 np.int64(5332),
 np.int64(6776),
 np.int64(8212),
 np.int64(8643),
 np.int64(8923),
 np.int64(9056),
 np.int64(9487),
 np.int64(11193),
 np.int64(12030),
 np.int64(15717),
 np.int64(16199),
 np.int64(16202),
 np.int64(16645),
 np.int64(17096),
 np.int64(17627),
 np.int64(17630),
 np.int64(17638),
 np.int64(18470),
 np.int64(19346),
 np.int64(19408),
 np.int64(20037),
 np.int64(21598),
 np.int64(23869),
 np.int64(25678),
 np.int64(27019),
 np.int64(27155),
 np.int64(43521),
 np.int64(49523),
 np.int64(50770),
 np.int64(54349),
 np.int64(56051),
 np.int64(63168),
 np.int64(63352),
 np.int64(63826),
 np.int64(67361),
 np.int64(72506),
 np.int64(75975),
 np.int64(83284),
 np.int64(83528),
 np.int64(83804),
 np.int64(107038),
 np.int64(129299),
 np.int64(132107),
 np.int64(143907),
 np.int64(144783),
 np.int64(146782),
 np.int64(190564),
 np.int64(196964),
 np.int64(203513),
 np.int64(225648),
 np.int64(273835),
 np.int64(283857),
 np.int64(283960),
 np.int64(296757),
 np.int64(492377),
 np.int64(498107),
 np.int64(508098),
 np.int64(967583)}

In [24]:
df = pd.read_csv(os.environ.get('PATH_OPENSKY') + '/results/agg_user_replies_news.csv', index_col=0)
#df.reset_index(names='user_id', inplace=True)
df

,instance,langs,min_date,max_date,mean_sent_score,mean_like_count,mean_reply_count,mean_repost_count,n_posts,replied_to_nos,caught_exception
288811,bsky.social,jpn,1976-05-31 14:49:40.250,1976-05-31 15:06:01.140,NaN,4.636364,0.000000,0.242424,33.0,NaN,False
527934,bsky.social,"jpn,heb,eng,fra",1976-05-30 12:23:51.918,1976-05-31 15:06:22.021,0.824409,18.211009,0.616972,7.187691,2616.0,NaN,False
1632691,bsky.social,spa,1976-05-30 13:16:31.226,1976-05-30 13:16:31.226,NaN,2.000000,1.000000,0.000000,1.0,NaN,False
1909409,bsky.social,jpn,1976-05-31 14:48:11.431,1976-05-31 14:48:11.431,NaN,1.000000,0.000000,0.000000,1.0,NaN,False
2902501,bsky.social,kor,1976-05-30 12:59:01.311,1976-05-31 14:51:00.209,NaN,0.500000,0.100000,0.000000,10.0,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
495380,bsky.social,eng,1976-05-30 12:40:30.146,1976-05-31 14:48:01.457,0.790667,0.800000,0.173333,0.026667,75.0,NaN,False
502241,bsky.social,eng,1976-05-31 14:47:42.021,1976-05-31 14:47:42.304,0.800889,3.777778,1.444444,1.222222,9.0,NaN,False
1652601,bsky.social,"jpn,spa,eng,cat",1976-05-30 12:09:11.814,1976-05-31 15:03:31.700,0.770500,87.579186,3.936652,33.321267,221.0,NaN,False
1838341,bsky.social,por,1976-05-30 12:23:50.927,1976-05-30 12:24:10.012,NaN,13.600000,1.400000,3.400000,5.0,NaN,False
3401925,esq,eng,1976-05-30 13:47:41.035,1976-05-31 15:05:40.127,0.727286,0.411765,0.215686,0.098039,51.0,NaN,False

In [26]:
df[678]

KeyError: 678

In [23]:
df.dropna(subset='replied_to_nos').user_id.sort_values()

153795          8
38874           9
4762           13
63706          24
513874         31
           ...
176697    4081842
257907    4082226
480619    4083399
655083    4087770
150153    4096128
Name: user_id, Length: 9300, dtype: int64

In [16]:
df = df.dropna(subset='replied_to_nos')

In [17]:
from tqdm.notebook import tqdm
tqdm.pandas()

df
df['path_file'] = df.user_id.apply(lambda x: PATH_USER_POSTS + str(x) + '.jsonl')
df['has_file'] = df.path_file.progress_apply(lambda x: os.path.exists(x))

/tmp/ipykernel_149709/3206483374.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['path_file'] = df.user_id.apply(lambda x: PATH_USER_POSTS + str(x) + '.jsonl')

  0%|          | 0/9300 [00:00<?, ?it/s]

/tmp/ipykernel_149709/3206483374.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_file'] = df.path_file.progress_apply(lambda x: os.path.exists(x))

In [21]:
df#.loc[df.user_id == 678, :]

,user_id,instance,langs,min_date,max_date,mean_sent_score,mean_like_count,mean_reply_count,mean_repost_count,n_posts,replied_to_nos,caught_exception,path_file,has_file
122,284413,bsky.social,"eng,ukr,deu",1976-05-30 13:13:41.329,1976-05-31 14:49:51.402,0.760353,4.047957,0.282416,1.134991,563.0,"15717,16202,25678,2486,6776,379,12030,319",False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
291,30401,bsky.social,"chr,por,rus,fra,ukr,afr,lat,fil,deu,aka,eng,it...",1976-05-30 11:50:50.303,1976-05-31 15:06:22.358,0.735840,89.697911,3.168092,26.569109,9239.0,"9,16202,17627,114,626,2486,379,319",False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
359,578933,bsky.social,eng,1976-05-30 13:33:41.138,1976-05-30 13:33:41.609,0.742500,1.500000,0.000000,0.000000,2.0,319,False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
374,776995,bsky.social,"eng,deu",1976-05-30 13:13:50.901,1976-05-31 15:05:50.752,0.777700,99.712000,4.448000,31.604000,250.0,9487,False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
499,485520,bsky.social,"zho,eng,tur,por,vie,nld,jpn,bre,fin,ita,fas,ru...",1976-05-30 12:24:11.515,1976-05-31 15:06:21.947,0.780523,73.118636,3.247984,22.851071,8682.0,"8643,319",False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705417,1848053,bsky.social,"heb,eng,ukr",1976-05-30 13:00:11.423,1976-05-30 13:35:00.725,0.751393,1.991736,0.570248,0.132231,121.0,2486,False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
705536,527683,bsky.social,"hye,eng,zho,por",1976-05-30 11:53:32.049,1976-05-31 15:06:21.836,0.746385,343.757048,11.076285,93.461028,1206.0,"379,319",False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
705569,347274,bsky.social,"eng,deu,fra,nld",1976-05-30 11:53:51.651,1976-05-31 15:06:22.327,0.758637,61.722299,1.729224,15.365651,2888.0,379,False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
705609,141248,bsky.social,"eng,rus,fra,ukr,deu",1976-05-30 13:34:01.205,1976-05-31 15:06:22.315,0.745130,37.720154,1.630295,9.184852,779.0,4890,False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True
705627,92560,bsky.social,"spa,eng,fra",1976-05-30 12:24:30.257,1976-05-31 15:06:22.230,0.742502,151.194313,4.561611,65.502370,422.0,"9,379",False,/home/ties/Documents/00_Uni/24W/Foundations/op...,True

In [10]:
df.has_file.sum()

np.int64(705683)

In [52]:
bm = [int(thread_root_author_id) in nos for thread_root_author_id in df.loc[30401, 'replied_to_nos'].split(',')]
bm

[True, True, True, True, True, True, True, True]

In [58]:
nos_ids = np.array(df.loc[30401, 'replied_to_nos'].split(','), dtype=int)

In [23]:
user_id = 30401
with open(PATH_USER_POSTS + str(user_id) + '.jsonl') as f:
    df_posts = pd.read_json(f, lines=True)

df_posts

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
0,40698497,30401,bsky.social,1976-05-31 15:06:22.358,www.pbs.org/video/art-o-...,[eng],1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.894
1,40698498,30401,bsky.social,1976-05-31 15:06:22.338,It's like saying there are good black people &...,[eng],1,0,0,697651.0,135.0,697651.0,135.0,NaN,NaN,NaN,NaN,NaN,0.0,0.550
2,40698499,30401,bsky.social,1976-05-31 15:06:22.328,youtu.be/qSARDlHh-Mg?...,[eng],1,0,0,40698500.0,30638.0,40698501.0,5750.0,NaN,NaN,NaN,NaN,NaN,1.0,0.763
3,40698502,30401,bsky.social,1976-05-31 15:06:22.320,youtu.be/xme1Vrc2ow0?...,[eng],1,0,0,40698500.0,30638.0,40698501.0,5750.0,NaN,NaN,NaN,NaN,NaN,1.0,0.757
4,40698503,30401,bsky.social,1976-05-31 15:06:22.314,when someone has the same taste in movies,[eng],2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9234,40710940,30401,bsky.social,1976-05-30 11:54:11.353,"As Kissinger turns 100, forget the birthday ca...",None,71,2,34,NaN,NaN,NaN,NaN,5855078.0,12286.0,NaN,NaN,NaN,NaN,NaN
9235,40710941,30401,bsky.social,1976-05-30 11:54:11.405,your reminder that Elon Musk is not an enginee...,None,18,1,3,NaN,NaN,NaN,NaN,1397416.0,7334.0,NaN,NaN,NaN,NaN,NaN
9236,40710942,30401,bsky.social,1976-05-30 11:54:11.318,Texas kids as young as 4 years old are being g...,None,61,17,34,NaN,NaN,NaN,NaN,6476411.0,628.0,NaN,NaN,NaN,NaN,NaN
9237,40710943,30401,bsky.social,1976-05-30 11:54:10.255,So many Twitter-esque accts. So little to say.,None,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9238,40710944,30401,bsky.social,1976-05-30 11:54:10.235,Most emails do.,None,0,0,0,24199715.0,49.0,24199715.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
set(df_posts.thread_root_author.unique()).intersection(nos_ids)

{np.int64(9),
 np.int64(114),
 np.int64(319),
 np.int64(379),
 np.int64(626),
 np.int64(2486),
 np.int64(16202),
 np.int64(17627)}

In [64]:
df_posts.loc[df_posts.thread_root_author.isin(nos), :]

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
458,40699100,30401,bsky.social,1976-05-31 15:04:32.208,Follow along below as President Biden delivers...,[eng],16,1,4,30903329.0,9.0,30903329.0,9.0,33750602.0,9.0,NaN,NaN,NaN,2.0,0.564
617,40699307,30401,bsky.social,1976-05-31 15:04:01.539,Primary ballots.,[eng],0,0,0,40699308.0,626.0,40699308.0,626.0,NaN,NaN,NaN,NaN,NaN,1.0,0.822
747,40699466,30401,bsky.social,1976-05-31 14:51:32.119,Underage girls would be more accurate wording.,[eng],12,0,0,9430000.0,9.0,378714.0,9.0,NaN,NaN,NaN,NaN,NaN,1.0,0.515
1402,40700339,30401,bsky.social,1976-05-31 14:48:42.223,Been watching your follower count climb for mo...,[eng],0,0,0,134087.0,9.0,134087.0,9.0,NaN,NaN,NaN,NaN,NaN,0.0,0.514
1524,40700505,30401,bsky.social,1976-05-31 14:48:10.044,Did the DOJ change its policy & it's now allow...,[eng],2,0,0,700921.0,379.0,700921.0,379.0,NaN,NaN,NaN,NaN,NaN,1.0,0.538
1863,40700981,30401,bsky.social,1976-05-31 14:35:11.933,Remember when they pretended to care about pub...,[eng],0,0,0,40700982.0,155002.0,3566040.0,319.0,NaN,NaN,NaN,NaN,NaN,0.0,0.815
2392,40701664,30401,bsky.social,1976-05-31 14:32:52.046,www.ebaumsworld.com/videos/alan-...,[eng],0,0,0,175843.0,114.0,175843.0,114.0,NaN,NaN,NaN,NaN,NaN,1.0,0.861
2492,40701804,30401,bsky.social,1976-05-31 14:32:32.130,Y'know what would be REALLY cool? The US PRETE...,[eng],1,0,0,40701805.0,2486.0,40701805.0,2486.0,NaN,NaN,NaN,NaN,NaN,0.0,0.607
2674,40702036,30401,bsky.social,1976-05-31 14:31:31.924,"""Bully frustrated by the ineffectiveness of hi...",[eng],25,0,1,144978.0,319.0,144978.0,319.0,NaN,NaN,NaN,NaN,NaN,0.0,0.899
3199,40702745,30401,bsky.social,1976-05-30 13:51:12.221,www.cnn.com/2007/POLITIC...,[eng],7,0,0,3144400.0,379.0,3144400.0,379.0,NaN,NaN,NaN,NaN,NaN,1.0,0.812
4174,40704030,30401,bsky.social,1976-05-30 13:47:31.823,"By not voting for yourself, you are in effect ...",[eng],6,0,0,1618305.0,319.0,1618305.0,319.0,NaN,NaN,NaN,NaN,NaN,0.0,0.770
4249,40704118,30401,bsky.social,1976-05-30 13:47:02.004,No one in charge of a company should be so ric...,[eng],0,0,0,284515.0,379.0,284515.0,379.0,NaN,NaN,NaN,NaN,NaN,0.0,0.826
5019,40705131,30401,bsky.social,1976-05-30 13:31:40.153,Republicans have the means to punish Tubervill...,[eng],0,0,0,29526381.0,16202.0,29526381.0,16202.0,NaN,NaN,NaN,NaN,NaN,0.0,0.835
5179,40705348,30401,bsky.social,1976-05-30 13:30:31.719,Otherwise what's the point?,[eng],0,0,0,40705349.0,7334.0,1677075.0,379.0,NaN,NaN,NaN,NaN,NaN,0.0,0.538
5221,40705403,30401,bsky.social,1976-05-30 13:30:21.702,Republicans don't give a shit about precedent....,[eng],7,0,0,24296739.0,66350.0,1677075.0,379.0,NaN,NaN,NaN,NaN,NaN,0.0,0.879
5222,40705401,30401,bsky.social,1976-05-30 13:30:21.659,"My issue is...even without actual convictions,...",[eng],3,1,0,24296740.0,7334.0,1677075.0,379.0,NaN,NaN,NaN,NaN,NaN,0.0,0.898
6174,40706647,30401,bsky.social,1976-05-30 13:00:22.105,https://bsky.app/profile/secretoriginz.bsky.so...,[eng],16,0,0,232848.0,379.0,232848.0,379.0,NaN,NaN,36267985.0,30401.0,NaN,1.0,0.656
6224,40706712,30401,bsky.social,1976-05-30 13:00:11.913,,[eng],7,0,0,3590377.0,319.0,3590377.0,319.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7719,40708834,30401,bsky.social,1976-05-30 12:40:12.210,You can read the full indictment here:,"[eng, spa]",69,1,17,2817452.0,319.0,2817452.0,319.0,8376929.0,319.0,NaN,NaN,NaN,NaN,NaN
9018,40710658,30401,bsky.social,1976-05-30 12:08:21.326,Trump gave Republicans permission to openly sh...,None,3,0,0,40710660.0,17627.0,40710660.0,17627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
(~df.replied_to_nos.isna()).sum()

np.int64(9300)

In [15]:
replied_to_nos_list = np.hstack([x.split(',') for x in list(df.replied_to_nos.dropna())]).astype(int)
reply_counts = pd.Series(replied_to_nos_list).value_counts()
reply_counts

379       3629
319       3050
9         1128
626        890
9487       719
          ...
50770        2
63352        2
283960       1
196964       1
296757       1
Name: count, Length: 70, dtype: int64

In [16]:
len(replied_to_nos_list)

14138

In [27]:
df = pd.read_csv(os.environ.get('PATH_OPENSKY') + '/results/agg_user_replies_news_posts.csv', index_col=0)

In [28]:
df

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
547,58817304,773,com,1976-05-31 14:51:21.252,"Well, hell. I daresay you've hit on something ...",['eng'],35,1,0,4859955.0,27155.0,4859955.0,27155.0,NaN,NaN,NaN,NaN,NaN,2.0,0.581
989,84174469,773,com,1976-05-31 14:48:51.445,"ah yes, Bluesky, that social media network tha...",['eng'],622,24,81,2414479.0,27155.0,2414479.0,27155.0,3199057.0,29537.0,NaN,NaN,NaN,0.0,0.630
2504,84175875,773,com,1976-05-30 13:48:52.354,My wife is 42 and she gives me the same expres...,['eng'],5,1,0,43649782.0,27155.0,43649782.0,27155.0,NaN,NaN,NaN,NaN,NaN,2.0,0.836
2624,58818971,773,com,1976-05-30 13:48:00.920,I think my own recent experience with Mastodon...,['eng'],2,1,0,58818983.0,27155.0,2174092.0,27155.0,NaN,NaN,NaN,NaN,NaN,0.0,0.793
12,16230650,5260,bsky.social,1976-05-31 15:06:22.349,ðŸŽ‰ðŸŽ‰ðŸŽ‰,['eng'],0,0,0,1571833.0,5332.0,1571833.0,5332.0,NaN,NaN,NaN,NaN,NaN,2.0,0.977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,172133889,316539,bsky.social,1976-05-31 14:34:40.229,In general the awful actions of any one person...,['eng'],6,0,0,117595846.0,125.0,2495405.0,379.0,NaN,NaN,NaN,NaN,NaN,0.0,0.922
826,13499048,320724,bsky.social,1976-05-31 14:48:40.640,"Yes Serbia, that great bastion of democracy wh...",['eng'],4,1,1,13499049.0,20037.0,13499049.0,20037.0,13499050.0,28062.0,NaN,NaN,NaN,1.0,0.415
1347,13499782,320724,bsky.social,1976-05-31 14:31:12.155,The Education Department said Bidenâ€™s policy c...,['eng'],20,0,8,9594493.0,319.0,9594493.0,319.0,13499783.0,62863.0,NaN,NaN,NaN,0.0,0.738
1390,13499840,320724,bsky.social,1976-05-31 14:30:52.037,The New York Times still has never reported th...,['eng'],259,3,72,83904.0,379.0,83904.0,379.0,717946.0,6793.0,NaN,NaN,NaN,0.0,0.667
167,181592162,326218,de,1976-05-30 13:16:30.857,"Es wÃ¼rde definitiv helfen, ein grosses Koordin...",['deu'],2,0,0,36185941.0,1537.0,36185941.0,1537.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
os.path.exists(PATH_USER_POSTS + '773.jsonl')

True